language: node_js
node_js:
  - '12'

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - node_modules/.bin/newman run collections/WDSM.postman_collection.json --color auto --disable-unicode
