language: node_js
node_js:
  - '12'

env:
  - jmeter_version: 5.2.1

jdk:
  - openjdk11

install:
  - npm install newman
  - wget http://ftp.cuhk.edu.hk/pub/packages/apache.org//jmeter/binaries/apache-jmeter-${jmeter_version}.tgz
  - tar -xzvf apache-jmeter-${jmeter_version}.tgz

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - node_modules/.bin/newman run collections/WDSM.postman_collection.json --color auto --disable-unicode
  - ./runScripts.sh ${jmeter_version}

